version: "3.8"
services:
  nlp-env:
    container_name: "nlp_env_container"
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: tabineko/nlp_env:v1
    volumes:
      - .:/home/nlp-class/
    tty: true
        